# The target name is most likely the name of your project.
platform :ios, '9.0'
use_frameworks!
target 'NumberTileGame' do


  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'DevSupport',
    'RCTAnimation',
    'RCTWebSocket', # needed for localhost testing of your app
    'BatchedBridge',
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'Firebase/Core'
end
